version: '3' #도커 컴포즈 파일 포맷을 최신 버전(3)으로 사용하겠다. AI는 3.8 추천했지만 어쨌거나 같은 주버전이기 때문에 괜찮음
#최신 도커는 이 줄 생략해도 알아서 최신으로 맞춰준다.

services:
  web: #실행할 서비스는 'web'(이름잉) 하나만.
    build: . #현재 폴더를 build할 것.
    command: python manage.py runserver 0.0.0.0:8000 #터미널에서 입력하던 서버 실행 command 입력. 그리고 주소는 로컬인 127.0.0.1 대신 외부 통신도 받는 0.0.0.0에 포트는 8000 유지.
    volumes: #로컬 컴퓨터의 폴더와 도커의 폴더를 연결. 여기서는 현재 폴더 ./와 도커의 workdir /usr/src/app/을 연결.
     - ./:/usr/src/app/
    ports: # 내 컴퓨터 포트 8000 : 컨테이너 내부 포트 8000 사용
     - 8000:8000 
    env_file: # 환경 설정 파일을 명시하면 settings.py에서 이 값을 불러와서 사용 가능. 지금은 개발환경만. 배포환경(.env.prod)는 나중에.
     - ./.env.dev
    depends_on:
     - db #db 컨테이너가 실행된 후에 이 web컨테이너가 실행되어야 함.
  db:
    image: postgres:15-alpine #교재는 12.0 알파인 사용했지만 나는 장고 5.2.5버전을 사용하기에 이것도 보다 최신버전으로.(가장 최신은 아님.)
    volumes: #이게 설정되어 있으면 컨테이너 종료되어도 DB내용은 보존됨.
     - postgres_data:/var/lib/postgresql/data/
    environment: #사용자명, 비밀번호, 데이터베이스명 지정.
     - POSTGRES_USER=do_it_django_db_user
     - POSTGRES_PASSWORD=do_it_django_db_password
     - POSTGRES_DB=do_it_django_dev #개발용 데이터베이스임.
volumes:
  postgres_data: