version: '3' #도커 컴포즈 파일 포맷을 최신 버전(3)으로 사용하겠다. AI는 3.8 추천했지만 어쨌거나 같은 주버전이기 때문에 괜찮음
#최신 도커는 이 줄 생략해도 알아서 최신으로 맞춰준다.

services:
  web: #실행할 서비스는 'web'(이름잉) 하나만.
    build: . #현재 폴더를 build할 것.
    command: python manage.py runserver 0.0.0.0:8000 #터미널에서 입력하던 서버 실행 command 입력. 그리고 주소는 로컬인 127.0.0.1 대신 외부 통신도 받는 0.0.0.0에 포트는 8000 유지.
    volumes: #로컬 컴퓨터의 폴더와 도커의 폴더를 연결. 여기서는 현재 폴더 ./와 도커의 workdir /usr/src/app/을 연결.
     - ./:/usr/src/app/
    ports: # 내 컴퓨터 포트 8000 : 컨테이너 내부 포트 8000 사용
     - 8000:8000 
    env_file: # 환경 설정 파일을 명시하면 settings.py에서 이 값을 불러와서 사용 가능. 지금은 개발환경만. 배포환경(.env.prod)는 나중에.
     - ./.env.dev